'use client';

import React, { useState } from 'react';
import { useRouter } from 'next/navigation';
import { CockpitLayout } from '@repo/ui/cockpit-layout';

export default function CustomerHome() {
  const [cpf, setCpf] = useState('');
  const [amount, setAmount] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  const handleCpfChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    let value = e.target.value.replace(/\D/g, '');
    if (value.length > 11) value = value.slice(0, 11);
    
    // Mask as XXX.XXX.XXX-XX
    if (value.length > 9) {
      value = `${value.slice(0, 3)}.${value.slice(3, 6)}.${value.slice(6, 9)}-${value.slice(9)}`;
    } else if (value.length > 6) {
      value = `${value.slice(0, 3)}.${value.slice(3, 6)}.${value.slice(6)}`;
    } else if (value.length > 3) {
      value = `${value.slice(0, 3)}.${value.slice(3)}`;
    }
    
    setCpf(value);
    setError(null);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const cleanCpf = cpf.replace(/\D/g, '');
    
    if (cleanCpf.length !== 11) {
      setError('Por favor, insira um CPF válido com 11 dígitos.');
      return;
    }

    if (!amount || parseFloat(amount) <= 0) {
      setError('Por favor, insira um valor solicitado válido maior que zero.');
      return;
    }

    setLoading(true);
    setError(null);

    // Call the actual Python resume_endpoint POST /analysis
    fetch('http://localhost:8086/analysis', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        cpf: cleanCpf,
        amount: parseFloat(amount),
      }),
    })
      .then((res) => {
        if (!res.ok) {
          throw new Error('Não foi possível inicializar a análise no orquestrador de crédito.');
        }
        return res.json();
      })
      .then((data) => {
        // Redirect with actual request_id generated by the backend!
        router.push(`/status/${data.request_id}?cpf=${encodeURIComponent(cpf)}&amount=${amount}`);
      })
      .catch((err) => {
        console.error('[CustomerHome] Error starting credit analysis:', err);
        setError(err instanceof Error ? err.message : 'Falha na conexão com o orquestrador multiagente.');
        setLoading(false);
      });
  };

  return (
    <CockpitLayout activeLink="proposal" portalType="customer">
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          minHeight: '70vh',
          animation: 'fadeIn 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        }}
      >
        <div
          style={{
            width: '100%',
            maxWidth: '520px',
            backgroundColor: 'var(--bg-card)',
            backdropFilter: 'blur(16px)',
            WebkitBackdropFilter: 'blur(16px)',
            padding: '3rem',
            borderRadius: '16px',
            border: 'var(--border-glass)',
            boxShadow: 'var(--shadow-main), inset 0 1px 1px hsla(0, 0%, 100%, 0.05)',
            transition: 'border-color 0.3s ease, box-shadow 0.3s ease, background 0.3s ease',
          }}
          onMouseOver={(e) => {
            e.currentTarget.style.borderColor = 'var(--border-glass-hover)';
            e.currentTarget.style.boxShadow = '0 20px 40px -15px rgba(0, 0, 0, 0.25), 0 0 20px var(--color-primary-glow)';
          }}
          onMouseOut={(e) => {
            e.currentTarget.style.borderColor = 'var(--border-glass)';
            e.currentTarget.style.boxShadow = 'var(--shadow-main)';
          }}
        >
          <div style={{ textAlign: 'center', marginBottom: '2.5rem' }}>
            <div
              className="glow-pulse-primary"
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                justifyContent: 'center',
                width: '60px',
                height: '60px',
                borderRadius: '16px',
                backgroundColor: 'var(--color-primary-glow)',
                color: 'var(--color-primary)',
                fontSize: '2rem',
                fontWeight: 900,
                marginBottom: '1.25rem',
                border: '1px solid var(--border-glass)',
                fontFamily: "var(--font-heading)",
              }}
            >
              $
            </div>
            <h1 
              style={{ 
                margin: 0, 
                fontSize: '1.75rem', 
                fontWeight: 800, 
                color: 'var(--text-primary)',
                fontFamily: "var(--font-heading)",
                letterSpacing: '-0.02em',
              }}
            >
              Crédito A2A Inteligente
            </h1>
            <p style={{ margin: '0.6rem 0 0 0', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
              Consulte sua proposta de crédito com aprovação multiagente em segundos
            </p>
          </div>

          <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.75rem' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <label 
                htmlFor="cpf" 
                style={{ 
                  fontSize: '0.75rem', 
                  fontWeight: 800, 
                  color: 'var(--text-secondary)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.08em',
                  fontFamily: "var(--font-heading)",
                }}
              >
                CPF do Titular
              </label>
              <input
                id="cpf"
                type="text"
                placeholder="000.000.000-00"
                value={cpf}
                onChange={handleCpfChange}
                disabled={loading}
                style={{
                  padding: '0.9rem 1.1rem',
                  borderRadius: '8px',
                  backgroundColor: 'hsla(0, 0%, 100%, 0.03)',
                  border: '1px solid var(--border-glass)',
                  color: 'var(--text-primary)',
                  fontSize: '1rem',
                  fontFamily: 'monospace',
                  letterSpacing: '0.05em',
                  outline: 'none',
                  transition: 'border-color 0.2s, box-shadow 0.2s',
                }}
                onFocus={(e) => {
                  e.currentTarget.style.borderColor = 'var(--color-primary)';
                  e.currentTarget.style.boxShadow = '0 0 10px var(--color-primary-glow)';
                }}
                onBlur={(e) => {
                  e.currentTarget.style.borderColor = 'var(--border-glass)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              />
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              <label 
                htmlFor="amount" 
                style={{ 
                  fontSize: '0.75rem', 
                  fontWeight: 800, 
                  color: 'var(--text-secondary)',
                  textTransform: 'uppercase',
                  letterSpacing: '0.08em',
                  fontFamily: "var(--font-heading)",
                }}
              >
                Valor Solicitado (R$)
              </label>
              <input
                id="amount"
                type="number"
                placeholder="Ex: 25000"
                value={amount}
                onChange={(e) => {
                  setAmount(e.target.value);
                  setError(null);
                }}
                disabled={loading}
                style={{
                  padding: '0.9rem 1.1rem',
                  borderRadius: '8px',
                  backgroundColor: 'hsla(0, 0%, 100%, 0.03)',
                  border: '1px solid var(--border-glass)',
                  color: 'var(--text-primary)',
                  fontSize: '1rem',
                  fontFamily: 'var(--font-primary)',
                  outline: 'none',
                  transition: 'border-color 0.2s, box-shadow 0.2s',
                }}
                onFocus={(e) => {
                  e.currentTarget.style.borderColor = 'var(--color-primary)';
                  e.currentTarget.style.boxShadow = '0 0 10px var(--color-primary-glow)';
                }}
                onBlur={(e) => {
                  e.currentTarget.style.borderColor = 'var(--border-glass)';
                  e.currentTarget.style.boxShadow = 'none';
                }}
              />
            </div>

            {error && (
              <div style={{ fontSize: '0.825rem', color: 'var(--color-rose)', fontWeight: 700 }}>
                ⚠️ {error}
              </div>
            )}

            <button
              type="submit"
              disabled={loading}
              style={{
                padding: '1rem',
                backgroundColor: loading ? 'hsla(0, 0%, 100%, 0.05)' : 'var(--color-primary)',
                color: '#FFFFFF',
                border: 'none',
                borderRadius: '8px',
                fontWeight: 800,
                fontSize: '1rem',
                fontFamily: "var(--font-heading)",
                cursor: loading ? 'not-allowed' : 'pointer',
                transition: 'background-color 0.2s, transform 0.2s, box-shadow 0.2s',
                boxShadow: loading ? 'none' : '0 4px 15px -3px var(--color-primary-glow)',
                marginTop: '0.5rem',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '0.5rem',
              }}
              onMouseOver={(e) => {
                if (!loading) {
                  e.currentTarget.style.backgroundColor = 'hsl(262, 80%, 52%)';
                  e.currentTarget.style.transform = 'translateY(-1px)';
                }
              }}
              onMouseOut={(e) => {
                if (!loading) {
                  e.currentTarget.style.backgroundColor = 'var(--color-primary)';
                  e.currentTarget.style.transform = 'translateY(0)';
                }
              }}
            >
              {loading && (
                <span 
                  style={{
                    width: '16px',
                    height: '16px',
                    border: '2.5px solid hsla(0, 0%, 100%, 0.2)',
                    borderTop: '2.5px solid #FFFFFF',
                    borderRadius: '50%',
                    animation: 'spin 0.8s linear infinite',
                    display: 'inline-block',
                  }}
                />
              )}
              {loading ? 'Inicializando Agentes...' : 'Iniciar Análise de Crédito'}
            </button>
          </form>
        </div>
      </div>
    </CockpitLayout>
  );
}
